blank_issues_enabled: true
contact_links:
  - name: Question, Discussion, Idea?
    url: https://github.com/lowdefy/lowdefy/discussions/new
    about: If you are unsure if the problem you are experiencing is a bug, or would like to request a feature, please rather create a discussion.
